project:
  type: book
  output-dir: "docs"
book:
  title: "PIP Manual"
  author: "PIP Technical Team"
  repo-url: https://github.com/PIP-Technical-Team/PIPmanual
  chapters:
    - part: "Welcome"
      chapters:
       - index.qmd
       - team.qmd
       - welcome.qmd
    - part: "Introduction"
      chapters:
        - intro.qmd
        - internal_workflow.qmd
        - Folder_structure.qmd
        - joining_data.qmd
    - part: "PIP data"
      chapters:
      - price_framework.qmd
      - PRIMUS.qmd
      - LIS.qmd
      - welfare_data.qmd
      - auxiliary_data.qmd
    - part: "PIP Procedures"
      chapters:
        - pc_pipeline.qmd
        - tm_pipeline.qmd
    - part: "Standalone Technical Considerations"
      chapters:
        - load_md_aux.qmd
        - docker.qmd
        - azure.qmd
        - workflows.qmd
        - subtrees.qmd
        - references.qmd

book_filename: "PIPmanual"
repo: https://github.com/PIP-Technical-Team/PIPmanual/
output_dir: "docs"
delete_merged_file: true
execute:
  freeze: auto
language:
  label:
    fig: "Figure "
    tab: "Table "
  ui:
    edit: "Edit"
    chapter_name: "Chapter "

qmd_files: [
  "index.qmd",
  "welcome.qmd",
  "team.qmd",
  "intro.qmd",
  "internal_workflow.qmd",
  "folder_structure.qmd",
  "joining_data.qmd",
  "price_framework.qmd",
  "PRIMUS.qmd",
  "LIS.qmd",
  "welfare_data.qmd",
  "auxiliary_data.qmd",
  "pc_pipeline.qmd",
  "tm_pipeline.qmd",
  "load_md_aux.qmd",
  "docker.qmd",
  "azure.qmd",
  "workflows.qmd",
  "subtrees.qmd",
  "references.qmd",
]

before_chapter_script: "_common.R"

